export const cars = [
  {
    brand: "Toyota",
    model: "Camry",
    year: 2022,
    price: "$24,000",
    colors: ["Red", "Blue", "Black"],
    PATH: "test/img/Toyota_Camry.png",
  },
  {
    brand: "Honda",
    model: "Civic",
    year: 2023,
    price: "$21,500",
    colors: ["White", "Gray", "Blue"],
    PATH: "test/img/Honda_Civic.png",
  },
  {
    brand: "Ford",
    model: "Mustang",
    year: 2023,
    price: "$28,000",
    colors: ["Black", "Silver", "Red"],
    PATH: "test/img/Ford_Mustang.png",
  },
  {
    brand: "Chevrolet",
    model: "Malibu",
    year: 2020,
    price: "$19,800",
    colors: ["Blue", "White", "Black"],
    PATH: "test/img/Chevrolet_Malibu.png",
  },
  {
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    price: "$35,000",
    colors: ["White", "Black", "Red"],
    PATH: "test/img/Tesla_Model 3.png",
  },
  {
    brand: "Tesla",
    model: "Model Y",
    year: 2020,
    price: "$42,000",
    colors: ["Black", "White", "Blue"],
    PATH: "test/img/Tesla_Model Y.png",
  },
];
